version: 2

updates:
  - package-ecosystem: cargo
    directory: /gateway
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    ignore:
      - dependency-name: rust
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5